name: Prueba

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: ${{ secrets.HEROKU_APP }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    #- name: Execute unitary tests
    #  run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test
    #- name: Execute APIREST tests
    #  run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
    #- name: Execute Selenium tests
    #  run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test
    #- name: Deploy Docker image
    #- name: Execute APIREST tests on Heroku
    #  run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' -Dhost=$HEROKU_APP.herokuapp.com test
    - name: Execute Selenium tests on Heroku
      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' -Dhost=$HEROKU_APP'.herokuapp.com' test
